import { ParallaxScroll } from "./parallaxScroll";

const tweets = [
  {
    username: "Dr. John Doe",
    handle: "drjohndoe",
    content: "Certigo made generating medical certificates effortless and efficient. Highly recommended for healthcare professionals!",
    avatar: "https://i.pravatar.cc/150?img=1",
  },
  {
    username: "Nurse Jane Smith",
    handle: "nursejanesmith",
    content: "The health badge creation with Certigo is smooth and user-friendly. Ideal for healthcare workers!",
    avatar: "https://i.pravatar.cc/150?img=2",
  },
  {
    username: "Dr. Bob Johnson",
    handle: "drbobjohnson",
    content: "Certigo simplifies the process of generating medical credentials. A great tool for healthcare institutions.",
    avatar: "https://i.pravatar.cc/150?img=3",
  },
  {
    username: "Dr. Alice Brown",
    handle: "dralicebrown",
    content: "Certigo helped me generate health certificates quickly and easily. Perfect for medical practice!",
    avatar: "https://i.pravatar.cc/150?img=4",
  },
  {
    username: "Charlie Davis, R.N.",
    handle: "charliedavisrn",
    content: "The health badge generation feature in Certigo is fantastic. Great tool for nursing staff!",
    avatar: "https://i.pravatar.cc/150?img=5",
  },
  {
    username: "Eva Wilson, Physio",
    handle: "evawilsonphysio",
    content: "The customization options for medical certificates are great. Certigo makes it easier to manage certifications.",
    avatar: "https://i.pravatar.cc/150?img=6",
  },
  {
    username: "Frank Martin, Healthcare Admin",
    handle: "frankmartinhealthcare",
    content: "Certigo's support team is exceptional. Medical certificate generation has never been easier!",
    avatar: "https://i.pravatar.cc/150?img=7",
  },
  {
    username: "Grace Lee, Therapist",
    handle: "graceleetherapist",
    content: "The certificates generated by Certigo have a professional and sleek design. Highly recommend for clinics!",
    avatar: "https://i.pravatar.cc/150?img=8",
  },
  {
    username: "Hannah White, Health Officer",
    handle: "hannahwhitehealth",
    content: "Integrating Certigo into my health clinic workflow made certificate generation a breeze. Great for health professionals!",
    avatar: "https://i.pravatar.cc/150?img=9",
  },
];

export function ParallaxScrollDemo() {
  return <ParallaxScroll tweets={tweets} />;
}
